In [13]:
import pandas as pd
df=pd.read_csv("insurance.csv")
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [14]:
df['region'].unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [15]:
df['sex'].unique()

array(['female', 'male'], dtype=object)

In [16]:
df['smoker'].unique()

array(['yes', 'no'], dtype=object)

In [17]:
maps={'southwest':0, 'southeast':1, 'northwest':2, 'northeast':3}
df['region']=df['region'].map(maps)

In [18]:
# fix the sex column
maps={'male':0, 'female':1}
df['sex']=df['sex'].map(maps)

In [19]:
# fix the smoker column
maps={'yes':0, 'no':1}
df['smoker']=df['smoker'].map(maps)

In [20]:
df

      age  sex     bmi  children  smoker  region      charges
0      19    1  27.900         0       0       0  16884.92400
1      18    0  33.770         1       1       1   1725.55230
2      28    0  33.000         3       1       1   4449.46200
3      33    0  22.705         0       1       2  21984.47061
4      32    0  28.880         0       1       2   3866.85520
...   ...  ...     ...       ...     ...     ...          ...
1333   50    0  30.970         3       1       2  10600.54830
1334   18    1  31.920         0       1       3   2205.98080
1335   18    1  36.850         0       1       1   1629.83350
1336   21    1  25.800         0       1       0   2007.94500
1337   61    1  29.070         0       0       2  29141.36030

[1338 rows x 7 columns]

In [21]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [ ]:
# Create new features BMI Category (Underweight/Normal/Overweight/Obese),Age Group, Interaction: smoker × BMI
def bmi_category(bmi):
    if bmi < 18.5:
        return 'Underweight'
    elif 18.5 <= bmi < 25:
        return 'Normal'
    elif 25 <= bmi < 30:
        return 'Overweight'
    else:
        return 'Obese'
df['BMI_Category'] = df['bmi'].apply(bmi_category)

def age_group(age):
    if age < 30:
        return 'Young'
    elif 30 <= age < 50:
        return 'Middle-aged'
    else:
        return 'Senior'
df['Age_Group']=df['age'].apply(age_group)
df['Smoker_BMI_Interaction']=df['smoker']*df['bmi']
df

,age,sex,bmi,children,smoker,region,charges,BMI_Category,Age_Group,Smoker_BMI_Interaction
0,19,1,27.900,0,0,0,16884.92400,Overweight,Young,0.000
1,18,0,33.770,1,1,1,1725.55230,Obese,Young,33.770
2,28,0,33.000,3,1,1,4449.46200,Obese,Young,33.000
3,33,0,22.705,0,1,2,21984.47061,Normal,Middle-aged,22.705
4,32,0,28.880,0,1,2,3866.85520,Overweight,Middle-aged,28.880
...,...,...,...,...,...,...,...,...,...,...
1333,50,0,30.970,3,1,2,10600.54830,Obese,Senior,30.970
1334,18,1,31.920,0,1,3,2205.98080,Obese,Young,31.920
1335,18,1,36.850,0,1,1,1629.83350,Obese,Young,36.850
1336,21,1,25.800,0,1,0,2007.94500,Overweight,Young,25.800
1337,61,1,29.070,0,0,2,29141.36030,Overweight,Senior,0.000